"""initial schema

Revision ID: e95d8153077c
Revises: 
Create Date: 2026-07-12 14:13:49.165181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95d8153077c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_pr_number'), 'reviews', ['pr_number'], unique=False)
    op.create_index(op.f('ix_reviews_repo'), 'reviews', ['repo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('github_avatar_url', sa.String(), nullable=True),
    sa.Column('github_name', sa.String(), nullable=True),
    sa.Column('github_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reviews_repo'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_pr_number'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
